replicaCount: 2

image:
  wordpress: wordpress:latest
  mysql: mysql:8.0

storage:
  size: 10Gi
  storageClass: "standard"

mysql:
  dbName: wordpress
  user: wordpress
  password: "strongpassword"
  rootPassword: "rootpassword"

ingress:
  enabled: true
  host: wordpress.local
  className: nginx

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 80
