version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    volumes:
      # Хранилище для данных БД на хост-машине
      - ./db_data:/var/lib/mysql
    environment:
      # Переменные окружения для настройки MySQL
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend # Сервис БД доступен только из внутренней сети

  app:
    # Используем образ, включающий PHP-FPM
    image: wordpress:latest-php8.1-fpm
    container_name: app
    restart: unless-stopped
    volumes:
      # Хранилище для файлов Wordpress на хост-машине
      - ./wordpress_html:/var/www/html
    environment:
      # Переменные окружения для подключения Wordpress к БД
      WORDPRESS_DB_HOST: db:3306 # Используем имя сервиса БД и порт
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
      - frontend # Сервис WP доступен как из backend, так и из frontend сети

  proxy:
    image: nginx:stable
    container_name: proxy
    restart: unless-stopped
    ports:
      # Проброс порта 80 хоста на порт 80 контейнера proxy
      - "80:80"
    volumes:
      # Монтирование файла конфигурации Nginx с хост-машины
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - frontend # Сервис proxy доступен из внешней сети и взаимодействует с app через frontend сеть

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
