apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-config
data:
  WORDPRESS_DB_HOST: {{ include "wordpress.fullname" . }}-mysql
  WORDPRESS_DB_USER: {{ .Values.mysql.user }}
  WORDPRESS_DB_NAME: {{ .Values.mysql.dbName }}
